### ISSUE TITLE
Can't see Back button in iOS 8 + iPhone 6

### ISSUE THREAD

**Issue by voznesenskym** [palmin/ios-multi-back-button#1]
Forked, will try to fix...

**Comment by palmin** [comment]
I do not have a iPhone 6, but just tried the example project with a iPhone 6 simulator and the back button looked just fine. 

Are you trying with the same project or a different one?

It is very easy to forget to include the image asset for ''<''.

**Comment by palmin** [comment]
![iphone-6](https://cloud.githubusercontent.com/assets/1230554/6418377/ee160466-beb4-11e4-8db7-a74c23137703.png)

**Comment by palmin** [comment]
The fix to https://github.com/palmin/ios-multi-back-button/issues/3 changed the way the back-button is drawn such that you do not need any image assets. 

Since I have not been able to reproduce this issue I will close it, but feel free to reopen with additional info if you are still having problems.
